apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-app-deployment
  labels:
    app: booking-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: booking-app
  template:
    metadata:
      labels:
        app: booking-app
    spec:
      # OPRAVA 1: Zmena na 'preferred', aby oba pody bežali na tvojom ASUS notebooku
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: booking-app
              topologyKey: "kubernetes.io/hostname"

      # OPRAVA 2: Musíš povedať Deploymentu, aby použil ten secret, čo už máš v klastri
      imagePullSecrets:
        - name: ghcr-login-secret

      containers:
      - name: booking-app-container
        image: bookingapp:latest
        ports:
        - containerPort: 8081
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: DATABASE_HOST
          value: postgresql-service
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: postgresql-user
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: postgresql-password
        - name: DATABASE_NAME
          value: booking_db
