apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-app-deployment
  labels:
    app: booking-app
spec:
  replicas: 2 # Pre vysokú dostupnosť
  selector:
    matchLabels:
      app: booking-app
  template:
    metadata:
      labels:
        app: booking-app
    spec:
      # Upravené na preferred, aby sa oba Pody zmestili na jeden Node (tvoj notebook)
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: booking-app
              topologyKey: "kubernetes.io/hostname"
      
      # Pridaný tajný kľúč pre prístup k GitHub Container Registry (GHCR)
      imagePullSecrets:
        - name: ghcr-login-secret

      containers:
      - name: booking-app-container
        # Tento placeholder prepisuješ v overlays/prod/booking-app/kustomization.yaml
        image: bookingapp:lates
        ports:
        - containerPort: 8081
        
        # Resource Limits pre stabilitu na ASUS notebooku
        resources:
          requests:
            memory: "64Mi" 
            cpu: "100m"
          limits:
            memory: "192Mi" 
            cpu: "500m"
        
        env:
        # Konfigurácia pripojenia k PostgreSQL
        - name: DATABASE_HOST
          value: postgresql-service
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: postgresql-user
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: postgresql-password
        - name: DATABASE_NAME
          value: booking_db
