apiVersion: v1
kind: Service
metadata:
  name: booking-app-service
  labels:
    app: booking-app
spec:
  type: ClusterIP
  selector:
    app: booking-app
  ports:
    - protocol: TCP
      port: 80         # Port, na ktorom počúva služba v klastri
      targetPort: 8080 # Musí smerovať na containerPort v Deploymente
      name: http
